---
title: "NewData"
output: html_document
date: "2022-11-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

This is the possible new data set collected from PISA in 2018 of USA students downloaded from the package "learning tower" developed by Kevin Wang. (Uncomment the code and install package in order to view)

```{r}
install.packages("learningtower")
```

```{r cars}
library(learningtower)

Pisa_2018 <- load_student(year = "2018")

Pisa_2018

summary(Pisa_2018$country)
library(dplyr)
USA_students <- Pisa_2018 %>% filter(`country` == "USA")

View(USA_students)
```

```{r}
library(tidyverse)
library (ggplot2)

USA_students <- USA_students %>%
  drop_na(internet)

USA_students %>%
  ggplot(aes(x = math , y = science , color = internet)) + geom_point() + coord_flip()
  
```
```{r}

USA_students <- USA_students %>%
  drop_na(computer)

USA_students %>%
  ggplot(aes(x = math , y = science , color = computer)) + geom_point() + coord_flip()
```

```{r}
USA_students$total_scores <- USA_students$math + USA_students$science + USA_students$read

USA_students %>%
  ggplot(aes(x = total_scores)) + geom_histogram(color = "red" , fill = "white" , binwidth = 15) + facet_grid(computer~internet , labeller = label_both)
```
```{r}
mean(USA_students$total_scores)
```



```{r}
USA_students<-USA_students %>%
drop_na(mother_educ,father_educ)
```

```{r}
table(USA_students$mother_educ)
table(USA_students$father_educ)
```

```{r}
high_educ<-USA_students %>% 
 filter(mother_educ=="ISCED 3A",father_educ=="ISCED 3A") %>% head()
high_educ
```

```{r}
mean(high_educ$math)
mean(high_educ$read)
mean(high_educ$science)
```

```{r}
low_educ<-USA_students %>% 
 filter(mother_educ=="less than ISCED1",father_educ=="less than ISCED1") %>% head()
low_educ
```

```{r}
mean(low_educ$math)
mean(low_educ$read)
mean(low_educ$science)
```

```{r}
USA_students %>%
  ggplot(aes(x=mother_educ, y=math,fill=father_educ)) + 
    geom_bar(position="dodge", stat="identity")
```
```{r}
USA_students %>%
  ggplot(aes(x=mother_educ, y=science,fill=father_educ)) + 
    geom_bar(position="dodge", stat="identity")
```

```{r}
USA_students %>%
  ggplot(aes(x=mother_educ, y=read,fill=father_educ)) + 
    geom_bar(position="dodge", stat="identity")
```
